name: Build and Deploy

# å½“æœ‰æ–° push æˆ–è€… PR æ—¶è¿è¡Œ
on:
  push:
    branches:
      - master
      - develop # æ·»åŠ å…¶ä»–åˆ†æ”¯ä»¥ä¾›å¼€å‘æµ‹è¯•
  pull_request:
    branches:
      - master
      - develop # æ·»åŠ å…¶ä»–åˆ†æ”¯ä»¥ä¾›å¼€å‘æµ‹è¯•

jobs:
  # ä¸€é¡¹å«åš build-and-deploy çš„ä»»åŠ¡
  build-and-deploy:
    # åœ¨æœ€æ–°ç‰ˆçš„ Ubuntu ç³»ç»Ÿä¸‹è¿è¡Œ
    runs-on: ubuntu-latest

    permissions:
      contents: write # å…è®¸å†™å…¥ä»“åº“å†…å®¹
      pages: write # å…è®¸å†™å…¥ GitHub Pages å†…å®¹
      id-token: write # å…è®¸å†™å…¥ ID Tokenï¼ˆå¦‚æœéœ€è¦ï¼‰

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # è·å–å®Œæ•´å†å²è®°å½•ï¼Œæœ‰åŠ©äºè°ƒè¯•

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Show environment variables
        run: env | sort

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          TOKEN: ${{ secrets.TOKEN }} # ä½¿ç”¨ GITHUB_TOKEN
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
